name: Automatic Build and Deployement

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Rebase branch
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git rebase origin/master
          
      - name: Build code
        uses: gradle/gradle-build-action@v2
        with:
          args: build
          
      - name: Push changes to default branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TELE_CHUBI }}
          branch: ${{ github.ref }}
          repository: Hans867/Bilabonnement-Eksamen-3SEM
